import Head from "next/head";
import styled from "@emotion/styled";
import { GetServerSidePropsContext } from "next/types";
import InferNextPropsType from "infer-next-props-type";
import { NextPageWithLayout } from "./_app";
import RootLayout from "../layouts/RootLayout";
import { ReactElement } from "react";

const Home: NextPageWithLayout<
  InferNextPropsType<typeof getServerSideProps>
> = (props) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>Vitro Admin</Title>
      <Name>{props.name}</Name>
    </Container>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <RootLayout>{page}</RootLayout>;
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      name: "example",
    },
  };
}

export default Home;

const Container = styled.div`
  padding: 0 2rem;
`;

const Title = styled.h1`
  color: #0070f3;
  text-decoration: none;

  :hover,
  :focus,
  :active {
    text-decoration: underline;
  }

  margin: 0;
  line-height: 1.15;
  font-size: 4rem;

  transition: all;
  transition-duration: 1s;
`;

const Name = styled.div`
  color: #eaeaea;
  text-decoration: none;
  :hover {
    color: #0070f3;
  }
  transition: color;
  transition-duration: 0.1s;
  height: 3000px;
`;
